//! Markdown report renderer.

use super::Report;

/// Render `report` as Markdown.
pub fn render(report: &Report) -> String {
    let mut out = String::new();

    out.push_str(&format!("# {}\n\n", report.title));
    out.push_str(&format!("**Session:** `{}`\n", report.session_id));
    out.push_str(&format!(
        "**Generated:** {}\n",
        report.generated_at.to_rfc3339()
    ));
    if let Some(scope) = &report.scope {
        out.push_str(&format!("**Scope:** {}\n", scope.summary()));
    }
    if !report.targets.is_empty() {
        out.push_str(&format!("**Targets:** {}\n", report.targets.join(", ")));
    }
    out.push('\n');

    out.push_str("## Summary\n\n");
    let total_findings = report.findings.len();
    if let Some(summary) = &report.summary {
        out.push_str(&format!(
            "- Steps completed: {} ({} skipped, {} failed)\n",
            summary.steps_completed, summary.steps_skipped, summary.steps_failed
        ));
        if !summary.tools_used.is_empty() {
            out.push_str(&format!(
                "- Tools used: {}\n",
                summary.tools_used.join(", ")
            ));
        }
    }
    out.push_str(&format!("- Evidence records: {}\n", report.evidence.len()));
    out.push_str(&format!("- Findings: {total_findings}\n"));
    let counts: Vec<String> = report
        .severity_counts()
        .into_iter()
        .filter(|(_, n)| *n > 0)
        .map(|(sev, n)| format!("{} × {n}", sev.as_str()))
        .collect();
    if !counts.is_empty() {
        out.push_str(&format!("- By severity: {}\n", counts.join(", ")));
    }
    out.push('\n');

    if !report.findings.is_empty() {
        out.push_str("## Findings\n\n");
        out.push_str("| Severity | Title | Confidence | Source | Target | Evidence |\n");
        out.push_str("| -------- | ----- | ---------- | ------ | ------ | -------- |\n");
        for finding in &report.findings {
            out.push_str(&format!(
                "| {} | {} | {:.0}% | {} | {} | {} |\n",
                finding.severity.as_str(),
                md_escape(&finding.title),
                finding.confidence * 100.0,
                finding.source.as_str(),
                md_escape(&finding.target),
                finding.evidence_ids.len(),
            ));
        }
        out.push('\n');

        for (index, finding) in report.findings.iter().enumerate() {
            out.push_str(&format!(
                "### {}. {} ({})\n\n",
                index + 1,
                md_escape(&finding.title),
                finding.severity.as_str()
            ));
            out.push_str(&format!(
                "- **Confidence:** {:.0}%\n",
                finding.confidence * 100.0
            ));
            out.push_str(&format!("- **Source:** {}\n", finding.source.as_str()));
            out.push_str(&format!("- **Target:** {}\n", md_escape(&finding.target)));
            out.push_str(&format!(
                "- **Evidence:** {}\n",
                finding.evidence_ids.join(", ")
            ));
            if let Some(category) = &finding.category {
                out.push_str(&format!("- **Category:** {category}\n"));
            }
            out.push('\n');
            if !finding.description.is_empty() {
                out.push_str(&format!("{}\n\n", md_escape(&finding.description)));
            }
            if let Some(recommendation) = &finding.recommendation {
                out.push_str(&format!(
                    "**Recommendation:** {}\n\n",
                    md_escape(recommendation)
                ));
            }
        }
    }

    if !report.evidence.is_empty() {
        out.push_str("## Evidence\n\n");
        for (index, item) in report.evidence.iter().enumerate() {
            out.push_str(&format!(
                "### {}. {} ({}) — {}\n\n",
                index + 1,
                item.r#type.as_str(),
                item.source,
                md_escape(&item.target),
            ));
            out.push_str(&format!("- **ID:** `{}`\n", item.id));
            out.push_str(&format!("- **SHA-256:** `{}`\n", item.sha256));
            if let Some(raw_ref) = &item.raw_ref {
                out.push_str(&format!("- **Raw output:** `{raw_ref}`\n"));
            }
            out.push_str(&format!(
                "- **Data:** `{}`\n\n",
                md_escape(&serde_json::to_string(&item.data).unwrap_or_default())
            ));
        }
    }

    out.push_str("---\n\n*Generated by ANAJAKKH — AI Red Team Security Agent.*\n");
    out
}

/// Escape characters that are special in Markdown table cells and emphasis.
fn md_escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evidence::{Evidence, EvidenceType};
    use crate::findings::{Finding, Severity};
    use std::path::PathBuf;

    fn report() -> Report {
        let finding = Finding::observed(
            "Telnet | exposed",
            Severity::High,
            "10.0.0.1",
            "cleartext",
            Some("use SSH".to_string()),
            vec!["ev-1".to_string()],
        );
        let evidence = Evidence::new(
            EvidenceType::Service,
            "nmap",
            "10.0.0.1",
            serde_json::json!({"port": 23}),
        );
        Report::new(
            "s1",
            PathBuf::from("/tmp"),
            None,
            vec!["10.0.0.1".to_string()],
            None,
            vec![evidence],
            vec![finding],
        )
    }

    #[test]
    fn markdown_includes_findings_and_evidence() {
        let md = render(&report());
        assert!(md.contains("## Findings"));
        assert!(md.contains("Telnet \\| exposed"));
        assert!(md.contains("high"));
        assert!(md.contains("## Evidence"));
        assert!(md.contains("ev-1"));
        assert!(md.contains("ANAJAKKH"));
    }

    #[test]
    fn empty_report_renders_safely() {
        let md = render(&Report::new(
            "s0",
            PathBuf::from("/tmp"),
            None,
            vec![],
            None,
            vec![],
            vec![],
        ));
        assert!(md.contains("Evidence records: 0"));
        assert!(md.contains("Findings: 0"));
    }

    #[test]
    fn severity_counts_appear() {
        let md = render(&report());
        assert!(md.contains("high × 1"));
    }
}
